//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int idTask { get; set; }
        public System.DateTime dateCreate { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public int typeTechnic { get; set; }
        public string modelTechnic { get; set; }
        public string description { get; set; }
        public string fioClient { get; set; }
        public string phoneClient { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> worker { get; set; }
    
        public virtual StatusesTasks StatusesTasks { get; set; }
        public virtual TypesTecnhic TypesTecnhic { get; set; }
        public virtual Users Users { get; set; }
    }
}
